server:
  port: 8080
---  
spring:
  cloud:
    gateway:
      routes:
#        - id: UserApi
#          uri: http://localhost:8082
#          predicates:
#            - Path=/users/**, /auth/signin

            



  
  
            